  - name: "coping software"
    copy:
       src: "./software"
       dest: "/"
   
  - name: "install hadoop software"
    shell: "rpm -ivh /software/hadoop-1.2.1-1.x86_64.rpm --force"

  - name: "install jdk software"
    shell: "rpm -i /software/jdk-8u171-linux-x64.rpm"
    ignore_errors: yes

  - name: "create a folder"
    file: 
       name: "{{ dir_namenode }}"
       state: directory

  - name: "configure hdfs file"
    template:
       src: "namenode_hdfs.xml"
       dest: "/etc/hadoop/hdfs-site.xml"

  - name: "configure core file"
    template:
       src: "namenode_core.xml"
       dest: "/etc/hadoop/core-site.xml"

  - name: "format namenode"
    shell: "echo Y | hadoop namenode -format"
    ignore_errors: yes

  - name: "start hadoop namenode service"
    command: "hadoop-daemon.sh start namenode"
    ignore_errors: yes

  - name: "enabling namenode service permanently"
    blockinfile:
            path: "/etc/rc.d/rc.local"
            block: |
                   hadoop-daemon.sh start namenode

  - name: "making file executable"
    shell: "chmod +x /etc/rc.d/rc.local"

  - name: "sending variables in datanode role"
    template:
            src: "varsfile.txt"
            dest: "/varsfile_namenode.txt"

  - name: "Reading variable file"
    shell: "cat /varsfile_namenode.txt"
    register: x

  - name: "sending variable in datanode role"
    local_action:
            copy
                 content="{{ x.stdout }}"
                 dest="./datanode/vars/main.yml"

  
  - name: "sending variable in jobtracker role"
    local_action:
            copy
                 content="{{ x.stdout }}"
                 dest="./jobtracker/vars/main.yml"


  - name: "sending client variables in jobtracker role"
    local_action:
         copy
                  content="{{ x.stdout }}"
                  dest="./jobtracker/templates/varsfile_client.txt"
