  - name: "coping software"
    copy:
       src: "./software"
       dest: "/"

  - name: "install hadoop software"
    shell: "rpm -i /software/hadoop-1.2.1-1.x86_64.rpm --force"

  - name: "install jdk software"
    shell: "rpm -i /software/jdk-8u171-linux-x64.rpm"
    ignore_errors: yes

  - name: "create a folder"
    file:
       name: "{{ dir_datanode }}"
       state: directory

  - name: "configure hdfs file"
    template:
       src: "datanode_hdfs.xml"
       dest: "/etc/hadoop/hdfs-site.xml"

  - name: "configure core file"
    template:
       src: "datanode_core.xml"
       dest: "/etc/hadoop/core-site.xml"

  - name: "matching cluster id"
    shell: "rm -rf {{ dir_datanode }}"

  - name: "matching cluster id"
    file:
       name: "{{ dir_datanode }}"
       state: directory

  - name: "start hadoop namenode service"
    command: "hadoop-daemon.sh start datanode"
    ignore_errors: yes

  - name: "enabling namenode service permanently"
    blockinfile:
            path: "/etc/rc.d/rc.local"
            block: |
                    hadoop-daemon.sh start datanode

  - name: "making file executable"
    shell: "chmod +x /etc/rc.d/rc.local"

                                               
